name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    env: 
      MONGODB_URI: ${{ vars.MONGODB_URI }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies 
        run: npm install  

      - name: Check style
        run: npm run eslint

      - name: Test
        run: npm run test

      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm start
          wait-on: http://localhost:3000

      - name: Deploy
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip')}}
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"